import { useState, useEffect } from 'react';
import { UploadCloud, FileSpreadsheet, CheckCircle, AlertCircle } from 'lucide-react';
import { api } from '../services/api';

export const AdminDashboard = () => {
  const [uploadState, setUploadState] = useState<'idle' | 'uploading' | 'validating' | 'ready' | 'error'>('idle');
  const [fileName, setFileName] = useState('');
  const [uploadStats, setUploadStats] = useState<any>(null);
  const [versionId, setVersionId] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [activeStats, setActiveStats] = useState<any>(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    api.checkAdminSession().then(auth => setIsAuthenticated(auth)).catch(console.error);
    api.getActiveMetadata().then(setActiveStats).catch(console.error);
  }, [uploadState]);

  const handleLogin = async () => {
    const pwd = prompt("Enter Admin Password:");
    if (pwd) {
      try {
        await api.loginAdmin(pwd);
        setIsAuthenticated(true);
      } catch (err: any) {
        alert(err.message);
      }
    }
  };

  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!isAuthenticated) {
       handleLogin();
       return;
    }
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];
      setFileName(file.name);
      setUploadState('uploading');
      
      try {
        const res = await api.uploadRoutine(file);
        setVersionId(res.version_id);
        setUploadStats(res.stats);
        setUploadState('ready');
      } catch (err: any) {
        setErrorMsg(err.message || "Failed to upload");
        setUploadState('error');
      }
    }
  };
  
  const handlePublish = async () => {
    try {
      await api.publishRoutine(versionId);
      alert('Routine Published Successfully');
      setUploadState('idle');
      api.getActiveMetadata().then(setActiveStats).catch(console.error);
    } catch (err: any) {
      alert("Failed to publish: " + err.message);
    }
  };

  return (
    <div className="space-y-8 pb-12">
      
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Dashboard Overview</h1>
          <p className="text-text-muted">Manage routine data and publish updates.</p>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="glass-panel p-5 rounded-xl border-t-2 border-t-accent">
          <p className="text-sm font-medium text-text-muted mb-1">Active Routine</p>
          <p className="text-xl font-bold text-white">{activeStats ? activeStats.semester : 'None'}</p>
        </div>
        <div className="glass-panel p-5 rounded-xl">
          <p className="text-sm font-medium text-text-muted mb-1">Total Batches</p>
          <p className="text-2xl font-bold text-white">{activeStats ? activeStats.batches_count : 0}</p>
        </div>
        <div className="glass-panel p-5 rounded-xl">
          <p className="text-sm font-medium text-text-muted mb-1">Total Sections</p>
          <p className="text-2xl font-bold text-white">{activeStats ? activeStats.sections_count : 0}</p>
        </div>
        <div className="glass-panel p-5 rounded-xl">
          <p className="text-sm font-medium text-text-muted mb-1">Total Classes</p>
          <p className="text-2xl font-bold text-white">{activeStats ? activeStats.classes_count : 0}</p>
        </div>
      </div>

      {/* Upload Section */}
      <div className="glass-panel p-6 sm:p-8 rounded-2xl max-w-3xl">
        <div className="mb-6">
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <UploadCloud className="text-accent" />
            Upload New Routine
          </h2>
          <p className="text-sm text-text-muted mt-1">
            Upload the latest CIS routine Excel file (.xlsx). The system will validate it before publishing.
          </p>
        </div>

        <div className="space-y-6">
          {uploadState === 'idle' && (
            <div className="border-2 border-dashed border-white/20 rounded-xl p-10 text-center hover:bg-white/5 transition-colors group relative cursor-pointer">
              <input 
                type="file" 
                accept=".xlsx, .xls" 
                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                onChange={handleUpload}
              />
              <FileSpreadsheet className="w-12 h-12 mx-auto text-text-muted group-hover:text-accent transition-colors mb-4" />
              <p className="text-lg font-medium text-white mb-1">Click or drag Excel file here</p>
              <p className="text-sm text-text-muted">Supports .xlsx files generated by CIS Dept</p>
              
              <button className="btn-secondary mt-6 pointer-events-none">
                Choose Excel File
              </button>
            </div>
          )}

          {uploadState === 'uploading' && (
            <div className="border border-white/10 bg-surface/50 rounded-xl p-6 flex items-center gap-4">
              <div className="w-12 h-12 rounded-full border-4 border-white/10 border-t-accent animate-spin shrink-0"></div>
              <div className="flex-1">
                <p className="text-lg font-medium text-white">Uploading & Parsing...</p>
                <p className="text-sm text-text-muted font-mono">{fileName}</p>
                <div className="w-full bg-background rounded-full h-2 mt-3 overflow-hidden">
                  <div className="bg-accent h-2 rounded-full transition-all duration-500 ease-out w-3/4 animate-pulse"></div>
                </div>
              </div>
            </div>
          )}
          
          {uploadState === 'error' && (
            <div className="border border-red-500/30 bg-red-500/10 rounded-xl p-6">
               <p className="text-lg font-medium text-red-400">Upload Failed</p>
               <p className="text-sm text-red-200/70 mt-1">{errorMsg}</p>
               <button className="btn-secondary mt-4" onClick={() => setUploadState('idle')}>Try Again</button>
            </div>
          )}

          {uploadState === 'ready' && uploadStats && (
            <div className="space-y-6">
              <div className="border border-green-500/30 bg-green-500/10 rounded-xl p-6">
                <div className="flex items-start gap-4 mb-4">
                  <CheckCircle className="w-6 h-6 text-green-400 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-lg font-medium text-white">Excel Processed Successfully</p>
                    <p className="text-sm text-green-200/70 mt-1">
                      "{fileName}" was parsed and is ready for review.
                    </p>
                  </div>
                </div>
                
                <div className="bg-background rounded-lg p-4 font-mono text-sm text-white/80 space-y-1">
                   <p>Batches detected: {uploadStats.batches}</p>
                   <p>Sections detected: {uploadStats.sections}</p>
                   <p>Classes parsed: {uploadStats.classes}</p>
                   <p className="text-yellow-400">Warnings: {uploadStats.warnings}</p>
                   <p className="text-blue-400">Duplicates removed: {uploadStats.duplicates}</p>
                </div>
              </div>

              <div className="flex flex-wrap gap-3">
                <button 
                  className="btn-primary flex items-center gap-2"
                  onClick={handlePublish}
                >
                  <UploadCloud className="w-4 h-4" />
                  Publish Routine
                </button>
                <button 
                  className="px-4 py-2 text-sm text-red-400 hover:text-red-300 hover:bg-red-400/10 rounded-lg transition-colors ml-auto"
                  onClick={() => setUploadState('idle')}
                >
                  Cancel
                </button>
              </div>
            </div>
          )}

          <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4 flex gap-3 text-sm">
            <AlertCircle className="w-5 h-5 text-blue-400 shrink-0" />
            <p className="text-blue-100">
              <strong>Note:</strong> Uploaded files are not automatically published. You must preview the parsed data and click Publish to update the student dashboard.
            </p>
          </div>

        </div>
      </div>
      
    </div>
  );
};
